// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.3
// source: github.com/amazingchow/photon-dance-snap/snappb/snap.proto

package snappb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type WalSnapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index uint64 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Term  uint64 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
}

func (x *WalSnapshot) Reset() {
	*x = WalSnapshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_amazingchow_photon_dance_snap_snappb_snap_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WalSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalSnapshot) ProtoMessage() {}

func (x *WalSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_amazingchow_photon_dance_snap_snappb_snap_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalSnapshot.ProtoReflect.Descriptor instead.
func (*WalSnapshot) Descriptor() ([]byte, []int) {
	return file_github_com_amazingchow_photon_dance_snap_snappb_snap_proto_rawDescGZIP(), []int{0}
}

func (x *WalSnapshot) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *WalSnapshot) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

type SnapshotMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index uint64 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Term  uint64 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
}

func (x *SnapshotMetadata) Reset() {
	*x = SnapshotMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_amazingchow_photon_dance_snap_snappb_snap_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnapshotMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotMetadata) ProtoMessage() {}

func (x *SnapshotMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_amazingchow_photon_dance_snap_snappb_snap_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotMetadata.ProtoReflect.Descriptor instead.
func (*SnapshotMetadata) Descriptor() ([]byte, []int) {
	return file_github_com_amazingchow_photon_dance_snap_snappb_snap_proto_rawDescGZIP(), []int{1}
}

func (x *SnapshotMetadata) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *SnapshotMetadata) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

type Snapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data     []byte            `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Metadata *SnapshotMetadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_amazingchow_photon_dance_snap_snappb_snap_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_amazingchow_photon_dance_snap_snappb_snap_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_github_com_amazingchow_photon_dance_snap_snappb_snap_proto_rawDescGZIP(), []int{2}
}

func (x *Snapshot) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Snapshot) GetMetadata() *SnapshotMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SavedSnapshot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Crc  uint32 `protobuf:"varint,1,opt,name=crc,proto3" json:"crc,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SavedSnapshot) Reset() {
	*x = SavedSnapshot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_amazingchow_photon_dance_snap_snappb_snap_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SavedSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SavedSnapshot) ProtoMessage() {}

func (x *SavedSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_amazingchow_photon_dance_snap_snappb_snap_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SavedSnapshot.ProtoReflect.Descriptor instead.
func (*SavedSnapshot) Descriptor() ([]byte, []int) {
	return file_github_com_amazingchow_photon_dance_snap_snappb_snap_proto_rawDescGZIP(), []int{3}
}

func (x *SavedSnapshot) GetCrc() uint32 {
	if x != nil {
		return x.Crc
	}
	return 0
}

func (x *SavedSnapshot) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_github_com_amazingchow_photon_dance_snap_snappb_snap_proto protoreflect.FileDescriptor

var file_github_com_amazingchow_photon_dance_snap_snappb_snap_proto_rawDesc = []byte{
	0x0a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6d, 0x61,
	0x7a, 0x69, 0x6e, 0x67, 0x63, 0x68, 0x6f, 0x77, 0x2f, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x6e, 0x2d,
	0x64, 0x61, 0x6e, 0x63, 0x65, 0x2d, 0x73, 0x6e, 0x61, 0x70, 0x2f, 0x73, 0x6e, 0x61, 0x70, 0x70,
	0x62, 0x2f, 0x73, 0x6e, 0x61, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x6e,
	0x61, 0x70, 0x70, 0x62, 0x22, 0x37, 0x0a, 0x0b, 0x57, 0x61, 0x6c, 0x53, 0x6e, 0x61, 0x70, 0x73,
	0x68, 0x6f, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x72,
	0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x74, 0x65, 0x72, 0x6d, 0x22, 0x3c, 0x0a,
	0x10, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x72, 0x6d, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x74, 0x65, 0x72, 0x6d, 0x22, 0x54, 0x0a, 0x08, 0x53,
	0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x34, 0x0a, 0x08, 0x6d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x73, 0x6e, 0x61, 0x70, 0x70, 0x62, 0x2e, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x35, 0x0a, 0x0d, 0x53, 0x61, 0x76, 0x65, 0x64, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68,
	0x6f, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x72, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x03, 0x63, 0x72, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6d, 0x61, 0x7a, 0x69, 0x6e, 0x67, 0x63, 0x68,
	0x6f, 0x77, 0x2f, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x6e, 0x2d, 0x64, 0x61, 0x6e, 0x63, 0x65, 0x2d,
	0x73, 0x6e, 0x61, 0x70, 0x2f, 0x73, 0x6e, 0x61, 0x70, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_github_com_amazingchow_photon_dance_snap_snappb_snap_proto_rawDescOnce sync.Once
	file_github_com_amazingchow_photon_dance_snap_snappb_snap_proto_rawDescData = file_github_com_amazingchow_photon_dance_snap_snappb_snap_proto_rawDesc
)

func file_github_com_amazingchow_photon_dance_snap_snappb_snap_proto_rawDescGZIP() []byte {
	file_github_com_amazingchow_photon_dance_snap_snappb_snap_proto_rawDescOnce.Do(func() {
		file_github_com_amazingchow_photon_dance_snap_snappb_snap_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_amazingchow_photon_dance_snap_snappb_snap_proto_rawDescData)
	})
	return file_github_com_amazingchow_photon_dance_snap_snappb_snap_proto_rawDescData
}

var file_github_com_amazingchow_photon_dance_snap_snappb_snap_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_github_com_amazingchow_photon_dance_snap_snappb_snap_proto_goTypes = []interface{}{
	(*WalSnapshot)(nil),      // 0: snappb.WalSnapshot
	(*SnapshotMetadata)(nil), // 1: snappb.SnapshotMetadata
	(*Snapshot)(nil),         // 2: snappb.Snapshot
	(*SavedSnapshot)(nil),    // 3: snappb.SavedSnapshot
}
var file_github_com_amazingchow_photon_dance_snap_snappb_snap_proto_depIdxs = []int32{
	1, // 0: snappb.Snapshot.metadata:type_name -> snappb.SnapshotMetadata
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_github_com_amazingchow_photon_dance_snap_snappb_snap_proto_init() }
func file_github_com_amazingchow_photon_dance_snap_snappb_snap_proto_init() {
	if File_github_com_amazingchow_photon_dance_snap_snappb_snap_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_amazingchow_photon_dance_snap_snappb_snap_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WalSnapshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_amazingchow_photon_dance_snap_snappb_snap_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnapshotMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_amazingchow_photon_dance_snap_snappb_snap_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Snapshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_amazingchow_photon_dance_snap_snappb_snap_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SavedSnapshot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_amazingchow_photon_dance_snap_snappb_snap_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_amazingchow_photon_dance_snap_snappb_snap_proto_goTypes,
		DependencyIndexes: file_github_com_amazingchow_photon_dance_snap_snappb_snap_proto_depIdxs,
		MessageInfos:      file_github_com_amazingchow_photon_dance_snap_snappb_snap_proto_msgTypes,
	}.Build()
	File_github_com_amazingchow_photon_dance_snap_snappb_snap_proto = out.File
	file_github_com_amazingchow_photon_dance_snap_snappb_snap_proto_rawDesc = nil
	file_github_com_amazingchow_photon_dance_snap_snappb_snap_proto_goTypes = nil
	file_github_com_amazingchow_photon_dance_snap_snappb_snap_proto_depIdxs = nil
}
